"""empty message

Revision ID: 8b1f67e48125
Revises: cfd1f6b46f2c
Create Date: 2022-05-28 21:32:12.703634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1f67e48125'
down_revision = 'cfd1f6b46f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=80), server_default='Your Name', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
