"""empty message

Revision ID: e4a98df6e9ce
Revises: 6a813ea31131
Create Date: 2022-05-24 20:52:25.184230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a98df6e9ce'
down_revision = '6a813ea31131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision', sa.Column('last_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision', 'last_checked')
    # ### end Alembic commands ###
